export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const RECORDING_STARTED = 'RECORDING_STARTED';
export const RECORDING_STOPPED = 'RECORDING_STOPPED';
export const PLAYBACK_STARTED = 'PLAYBACK_STARTED';
export const PLAYBACK_STOPPED = 'PLAYBACK_STOPPED';
