export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const RECORD_MESSAGE = 'RECORD_MESSAGE';
export const PLAYBACK_STARTED = 'PLAYBACK_STARTED';
export const PLAYBACK_STOPPED = 'PLAYBACK_STOPPED';
